#spring:
#  autoconfigure:
#    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.cache.type: redis
rate-providers:
  open-exchange:
    base-url: "https://openexchangerates.org/api"
    application-id: ${OPEN_EXCHANGE_RATES_APP_ID}
